//
// Generated file, do not edit! Created by opp_msgc 4.2 from ansa/switch/stp/STPTCN.msg.
//

#ifndef _STPTCN_M_H_
#define _STPTCN_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ansa/switch/stp/STPTCN.msg</tt> by opp_msgc.
 * <pre>
 * packet STPTCN {
 * 	unsigned int vlan;
 * }
 * </pre>
 */
class STPTCN : public ::cPacket
{
  protected:
    unsigned int vlan_var;

  private:
    void copy(const STPTCN& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const STPTCN&);

  public:
    STPTCN(const char *name=NULL, int kind=0);
    STPTCN(const STPTCN& other);
    virtual ~STPTCN();
    STPTCN& operator=(const STPTCN& other);
    virtual STPTCN *dup() const {return new STPTCN(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getVlan() const;
    virtual void setVlan(unsigned int vlan);
};

inline void doPacking(cCommBuffer *b, STPTCN& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, STPTCN& obj) {obj.parsimUnpack(b);}


#endif // _STPTCN_M_H_
