//
// Generated file, do not edit! Created by opp_msgc 4.2 from ansa/switch/AnsaEtherFrame.msg.
//

#ifndef _ANSAETHERFRAME_M_H_
#define _ANSAETHERFRAME_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Ethernet.h"
#include "MACAddress.h"
#include "Ieee802Ctrl_m.h" 
#include "EtherFrame_m.h"
// }}



/**
 * Class generated from <tt>ansa/switch/AnsaEtherFrame.msg</tt> by opp_msgc.
 * <pre>
 * packet AnsaEtherFrame extends EthernetIIFrame
 * {
 *     int vlan;
 *     
 *     string displayString = "b=,,,kind,kind,0";
 * }
 * </pre>
 */
class AnsaEtherFrame : public ::EthernetIIFrame
{
  protected:
    int vlan_var;
    opp_string displayString_var;

  private:
    void copy(const AnsaEtherFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AnsaEtherFrame&);

  public:
    AnsaEtherFrame(const char *name=NULL, int kind=0);
    AnsaEtherFrame(const AnsaEtherFrame& other);
    virtual ~AnsaEtherFrame();
    AnsaEtherFrame& operator=(const AnsaEtherFrame& other);
    virtual AnsaEtherFrame *dup() const {return new AnsaEtherFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getVlan() const;
    virtual void setVlan(int vlan);
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
};

inline void doPacking(cCommBuffer *b, AnsaEtherFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, AnsaEtherFrame& obj) {obj.parsimUnpack(b);}


#endif // _ANSAETHERFRAME_M_H_
