//
// Generated file, do not edit! Created by opp_msgc 4.2 from ansa/ospfv3/messages/ansaOspfTimer6.msg.
//

#ifndef _ANSAOSPFTIMER6_M_H_
#define _ANSAOSPFTIMER6_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "INETDefs.h"
// }}



/**
 * Enum generated from <tt>ansa/ospfv3/messages/ansaOspfTimer6.msg</tt> by opp_msgc.
 * <pre>
 * enum OspfTimerType6 {
 *    InterfaceHelloTimer = 0;
 *    InterfaceWaitTimer = 1;
 *    InterfaceAcknowledgementTimer = 3;
 *    NeighborInactivityTimer = 4;
 *    NeighborPollTimer = 5;
 *    NeighborDDRetransmissionTimer = 6;
 *    NeighborUpdateRetransmissionTimer = 7;
 *    NeighborRequestRetransmissionTimer = 8;
 *    DatabaseAgeTimer = 9;
 * }
 * </pre>
 */
enum OspfTimerType6 {
    InterfaceHelloTimer = 0,
    InterfaceWaitTimer = 1,
    InterfaceAcknowledgementTimer = 3,
    NeighborInactivityTimer = 4,
    NeighborPollTimer = 5,
    NeighborDDRetransmissionTimer = 6,
    NeighborUpdateRetransmissionTimer = 7,
    NeighborRequestRetransmissionTimer = 8,
    DatabaseAgeTimer = 9
};

/**
 * Class generated from <tt>ansa/ospfv3/messages/ansaOspfTimer6.msg</tt> by opp_msgc.
 * <pre>
 * packet OspfTimer6 extends cMessage {
 * 	char timerKind enum(OspfTimerType6) = InterfaceHelloTimer;
 * }
 * </pre>
 */
class OspfTimer6 : public ::cMessage
{
  protected:
    char timerKind_var;

  private:
    void copy(const OspfTimer6& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OspfTimer6&);

  public:
    OspfTimer6(const char *name=NULL, int kind=0);
    OspfTimer6(const OspfTimer6& other);
    virtual ~OspfTimer6();
    OspfTimer6& operator=(const OspfTimer6& other);
    virtual OspfTimer6 *dup() const {return new OspfTimer6(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual char getTimerKind() const;
    virtual void setTimerKind(char timerKind);
};

inline void doPacking(cCommBuffer *b, OspfTimer6& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OspfTimer6& obj) {obj.parsimUnpack(b);}


#endif // _ANSAOSPFTIMER6_M_H_
